name: api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  google_generative_ai: ^0.4.6
  dart_frog_web_socket: ^1.0.0
  envied: ^0.5.4+1
  model:
    path: ../packages/model

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.12
